### ISSUE TITLE
How to Read YUV Files

### ISSUE THREAD

**Issue by cianhwang** [ultravideo/UVG-4K-Dataset#1]
Thank you for the excellent dataset! I was just wondering how to read these raw files with subfix .yuv? Any sample code or idea would be appreciated.

**Comment by fador** [comment]
Hi,

Thank you!

YUV is well defined raw video format: [https://wiki.videolan.org/YUV](https://wiki.videolan.org/YUV)
Basically for each frame there is Width*Height luma pixels and after those (Width/2)*(Height/2) Chroma U and the same amount of Chroma V

Easiest way to see these raw YUV files is using [YUView](https://github.com/IENT/YUView/releases)

If you want to use FFmpeg, it works like this:
`ffmpeg -f rawvideo -vcodec rawvideo -s <WIDTH>x<HEIGHT> -r 120 -pix_fmt yuv420p -i inputfile.yuv ...`

I hope this helps!

**Comment by cianhwang** [comment]
Thank you! Will try shortly.

**Comment by merlinyz** [comment]
First of all, thank you very much for the dataset! I was wondering how did you create these .yuv and .y4m files from images? Since I'd like to create the yuv/y4m file with my own image sequences, especially the 10bit and 12bit yuv. Thanks in advance!
