### ISSUE TITLE
Create my own y4m files

### ISSUE THREAD

**Issue by merlinyz** [ultravideo/UVG-4K-Dataset#2]
First of all, thank you very much for the dataset! I was wondering how did you create these .yuv and .y4m files from images? Since I'd like to create the yuv/y4m file with my own image sequences, especially the 10bit and 12bit yuv. Thanks in advance!

**Comment by fador** [comment]
Hi,

Thank you!

We used `ffmpeg` for this task, basically you can do 10bit yuv output like this:
`ffmpeg -start_number 0 -i sequence_%05d.png -pix_fmt yuv420p10 sequence_name_3840x2160_10bit.yuv`

Where you should have images named in format `sequence_00000.png`

Replace `yuv420p10` with `yuv420p12` for 12-bit output and you can use `yuv444p10` and `yuv444p12` for YUV 4:4:4 chroma subsampling format.

**Comment by merlinyz** [comment]
Hi, Thank you very much for the information!
